CREATE TABLE joueur1 (
    id INT AUTO_INCREMENT PRIMARY KEY,
    score INT DEFAULT 0,
    checked INT DEFAULT 0,
    boat INT DEFAULT 0
);

CREATE TABLE joueur2 (
    id INT AUTO_INCREMENT PRIMARY KEY,
    score INT DEFAULT 0,
    checked INT DEFAULT 0,
    boat INT DEFAULT 0
);

CREATE TABLE partie (id INT AUTO_INCREMENT PRIMARY KEY, date TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE grille (id INT AUTO_INCREMENT PRIMARY KEY, joueur_id INT, x INT, y INT, etat INT DEFAULT 0);

INSERT INTO joueur1 (id, checked)
VALUES
(1, 0),
(2, 0),
(3, 0),
(4, 0);
